v = input("Digite algo:")
print('O tipo primitivo desse valor é {}'.format(type(v)))
print('Só tem espaços?', v.isspace())
print('É um número?', v.isnumeric())
print('É alfabetico?', v.isalpha())
print('É alfanumerico?', v.isalnum())
print('Está em maiúsculas?', v.isupper())
print('Está em minúsculas?', v.islower())
print('Está capitalizada?', v.istitle())
